### YamlMime:ModuleUnit
uid: learn.pillars-of-a-great-azure-architecture.3-design-for-security
title: <span data-ttu-id="7e9d3-101">보안을 위해 설계</span><span class="sxs-lookup"><span data-stu-id="7e9d3-101">Design for security</span></span>
metadata:
  title: <span data-ttu-id="7e9d3-102">보안을 위해 설계</span><span class="sxs-lookup"><span data-stu-id="7e9d3-102">Design for security</span></span>
  description: <span data-ttu-id="7e9d3-103">보안을 위해 설계</span><span class="sxs-lookup"><span data-stu-id="7e9d3-103">Design for security</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: b1f1fd5afaa153340eee740bd0071fc8295c63e6
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44245718"
durationInMinutes: 10
content: >
  [!include[](includes/3-design-for-security.md)]
quiz:
  title: <span data-ttu-id="7e9d3-104">지식 검사 - 보안을 위한 설계</span><span class="sxs-lookup"><span data-stu-id="7e9d3-104">Knowledge check - Design for security</span></span>
  questions:
  - content: <span data-ttu-id="7e9d3-105">다음 유형의 데이터 중 보안 보호가 있을 수 있는 것은 무엇인가요?</span><span class="sxs-lookup"><span data-stu-id="7e9d3-105">Which of the following types of data may need to have security protections?</span></span>
    choices:
    - content: <span data-ttu-id="7e9d3-106">개인 정보를 포함하는 고객 데이터</span><span class="sxs-lookup"><span data-stu-id="7e9d3-106">Customer data that contains personal information</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="7e9d3-107">이 데이터에 대한 적절한 보안 보호 기능을 제공해야 하지만 이것만이 올바른 선택은 아닙니다.</span><span class="sxs-lookup"><span data-stu-id="7e9d3-107">It is important to provide proper security protections for this data, but this is not the only correct choice.</span></span>
    - content: <span data-ttu-id="7e9d3-108">비즈니스 작업을 지원하는 재무 데이터</span><span class="sxs-lookup"><span data-stu-id="7e9d3-108">Financial data supporting business operations</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="7e9d3-109">이 데이터에 대한 적절한 보안 보호 기능을 제공해야 하지만 이것만이 올바른 선택은 아닙니다.</span><span class="sxs-lookup"><span data-stu-id="7e9d3-109">It is important to provide proper security protections for this data, but this is not the only correct choice.</span></span>
    - content: <span data-ttu-id="7e9d3-110">지적 재산권을 포함하는 데이터</span><span class="sxs-lookup"><span data-stu-id="7e9d3-110">Data containing intellectual property</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="7e9d3-111">이 데이터에 대한 적절한 보안 보호 기능을 제공해야 하지만 이것만이 올바른 선택은 아닙니다.</span><span class="sxs-lookup"><span data-stu-id="7e9d3-111">It is important to provide proper security protections for this data, but this is not the only correct choice.</span></span>
    - content: <span data-ttu-id="7e9d3-112">위의 모든 것은 보안 보호 필요</span><span class="sxs-lookup"><span data-stu-id="7e9d3-112">All of the above may need security protections</span></span>
      isCorrect: true
      correctExplanation: <span data-ttu-id="7e9d3-113">위의 모든 것에는 추가 보안 보호가 필요할 수 있습니다.</span><span class="sxs-lookup"><span data-stu-id="7e9d3-113">All of the above may merit additional security protections.</span></span>
  - content: <span data-ttu-id="7e9d3-114">다음 중 경계 계층에 표시될 수 있는 공격의 예는 무엇입니까?</span><span class="sxs-lookup"><span data-stu-id="7e9d3-114">Which of the following is an example of an attack you might see at the perimeter layer?</span></span>
    choices:
    - content: <span data-ttu-id="7e9d3-115">온라인에 게시된 자격 증명 노출</span><span class="sxs-lookup"><span data-stu-id="7e9d3-115">Exposed credentials posted online</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="7e9d3-116">노출된 자격 증명은 조직에 큰 위험이 되지만 경계 공격은 아닙니다.</span><span class="sxs-lookup"><span data-stu-id="7e9d3-116">Exposed credentials are a huge risk to an organization, but are not a permiter attack.</span></span>
    - content: <span data-ttu-id="7e9d3-117">SYN 도배 공격</span><span class="sxs-lookup"><span data-stu-id="7e9d3-117">A SYN flood attack</span></span>
      isCorrect: true
      correctExplanation: <span data-ttu-id="7e9d3-118">SYN 도배 공격은 네트워크 경계에서 흔히 보이는 서비스 거부 공격 유형입니다.</span><span class="sxs-lookup"><span data-stu-id="7e9d3-118">SYN flood attacks are a type of denial-of-service attack that are commonly seen on the network perimeter.</span></span>
    - content: <span data-ttu-id="7e9d3-119">데이터 센터에 이르기 위한 도어 드래프팅</span><span class="sxs-lookup"><span data-stu-id="7e9d3-119">Door drafting to get into a datacenter</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="7e9d3-120">도어 드래프팅은 물리적 계층 공격입니다.</span><span class="sxs-lookup"><span data-stu-id="7e9d3-120">Door drafting is a physical layer attack.</span></span>
    - content: <span data-ttu-id="7e9d3-121">가상 머신의 디스크를 암호화하는 랜섬웨어</span><span class="sxs-lookup"><span data-stu-id="7e9d3-121">Ransomware that encrypts the disks of a virtual machine</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="7e9d3-122">랜섬웨어 공격은 VM/계산 계층 공격입니다.</span><span class="sxs-lookup"><span data-stu-id="7e9d3-122">Ransomware attacks are a VM/compute layer attack.</span></span>
