### YamlMime:ModuleUnit
uid: learn.pillars-of-a-great-azure-architecture.3-design-for-security
title: <span data-ttu-id="7b24d-101">보안을 위해 설계</span><span class="sxs-lookup"><span data-stu-id="7b24d-101">Design for security</span></span>
metadata:
  title: <span data-ttu-id="7b24d-102">보안을 위해 설계</span><span class="sxs-lookup"><span data-stu-id="7b24d-102">Design for security</span></span>
  description: <span data-ttu-id="7b24d-103">보안을 위한 설계</span><span class="sxs-lookup"><span data-stu-id="7b24d-103">Design for security</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 1b55aacd394eb8f956c0b0ef45713cdcc57a03b0
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47142326"
durationInMinutes: 10
content: >
  [!include[](includes/3-design-for-security.md)]
quiz:
  title: <span data-ttu-id="7b24d-104">지식 검사</span><span class="sxs-lookup"><span data-stu-id="7b24d-104">Check your knowledge</span></span>
  questions:
  - content: <span data-ttu-id="7b24d-105">다음 유형의 데이터 중 보안 보호가 필요한 것은 무엇인가요?</span><span class="sxs-lookup"><span data-stu-id="7b24d-105">Which of the following types of data may need to have security protections?</span></span>
    choices:
    - content: <span data-ttu-id="7b24d-106">개인 정보를 포함하는 고객 데이터</span><span class="sxs-lookup"><span data-stu-id="7b24d-106">Customer data that contains personal information</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="7b24d-107">이 데이터에 대한 적절한 보안 보호 기능을 제공해야 하지만 이것만이 올바른 선택은 아닙니다.</span><span class="sxs-lookup"><span data-stu-id="7b24d-107">It is important to provide proper security protections for this data, but this is not the only correct choice.</span></span>
    - content: <span data-ttu-id="7b24d-108">비즈니스 작업을 지원하는 재무 데이터</span><span class="sxs-lookup"><span data-stu-id="7b24d-108">Financial data supporting business operations</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="7b24d-109">이 데이터에 대한 적절한 보안 보호를 제공해야 하지만 이것만 유일한 올바른 선택은 아닙니다.</span><span class="sxs-lookup"><span data-stu-id="7b24d-109">It is important to provide proper security protections for this data, but this is not the only correct choice.</span></span>
    - content: <span data-ttu-id="7b24d-110">지적 재산권</span><span class="sxs-lookup"><span data-stu-id="7b24d-110">Intellectual property</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="7b24d-111">이 데이터에 대한 적절한 보안 보호를 제공해야 하지만 이것만 유일한 올바른 선택은 아닙니다.</span><span class="sxs-lookup"><span data-stu-id="7b24d-111">It is important to provide proper security protections for this data, but this is not the only correct choice.</span></span>
    - content: <span data-ttu-id="7b24d-112">위의 모든 것은 보안 보호 필요</span><span class="sxs-lookup"><span data-stu-id="7b24d-112">All of the above may need security protections</span></span>
      isCorrect: true
      correctExplanation: <span data-ttu-id="7b24d-113">위의 모든 것에는 추가 보안 보호가 필요할 수 있습니다.</span><span class="sxs-lookup"><span data-stu-id="7b24d-113">All of the above may merit additional security protections.</span></span>
  - content: <span data-ttu-id="7b24d-114">다음 중 정책 및 액세스 계층에 표시될 수 있는 공격의 예제는 무엇인가요?</span><span class="sxs-lookup"><span data-stu-id="7b24d-114">Which of the following is an example of an attack you might see at the policies & access layer?</span></span>
    choices:
    - content: <span data-ttu-id="7b24d-115">온라인에 게시된 자격 증명 노출</span><span class="sxs-lookup"><span data-stu-id="7b24d-115">Exposed credentials posted online</span></span>
      isCorrect: true
      correctExplanation: <span data-ttu-id="7b24d-116">노출된 자격 증명은 조직에 커다란 위험이며 정책 및 액세스 계층에 적용됩니다.</span><span class="sxs-lookup"><span data-stu-id="7b24d-116">Exposed credentials are a huge risk to an organization and apply at the policies & access layer.</span></span>
    - content: <span data-ttu-id="7b24d-117">SYN 도배 공격</span><span class="sxs-lookup"><span data-stu-id="7b24d-117">A SYN flood attack</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="7b24d-118">SYN 도배 공격은 네트워크 경계에서 흔히 확인되는 서비스 거부 공격 형식입니다.</span><span class="sxs-lookup"><span data-stu-id="7b24d-118">SYN flood attacks are a type of denial-of-service attack that are commonly seen on the network perimeter.</span></span>
    - content: <span data-ttu-id="7b24d-119">자격 증명을 입력하지 않고 직원을 따라 데이터 센터로 침입</span><span class="sxs-lookup"><span data-stu-id="7b24d-119">Following an employee into a datacenter without presenting credentials</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="7b24d-120">직원을 따라 데이터 센터로 침입하는 것은 물리적 계층 공격입니다.</span><span class="sxs-lookup"><span data-stu-id="7b24d-120">Following an employee into a datacenter is a physical layer attack.</span></span>
    - content: <span data-ttu-id="7b24d-121">가상 머신의 디스크를 암호화하는 랜섬웨어</span><span class="sxs-lookup"><span data-stu-id="7b24d-121">Ransomware that encrypts the disks of a virtual machine</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="7b24d-122">랜섬웨어 공격은 VM/계산 계층 공격입니다.</span><span class="sxs-lookup"><span data-stu-id="7b24d-122">Ransomware attacks are a VM/compute layer attack.</span></span>
