### YamlMime:ModuleUnit
uid: learn.principles-cloud-computing.4-cloud-deployment-models
title: <span data-ttu-id="95eaf-101">클라우드 배포 모델</span><span class="sxs-lookup"><span data-stu-id="95eaf-101">Cloud deployment models</span></span>
metadata:
  title: <span data-ttu-id="95eaf-102">클라우드 배포 모델</span><span class="sxs-lookup"><span data-stu-id="95eaf-102">Cloud deployment models</span></span>
  description: <span data-ttu-id="95eaf-103">클라우드 배포 모델</span><span class="sxs-lookup"><span data-stu-id="95eaf-103">Cloud deployment models</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 80c9a95833f8fb5be1e0e89b4729b0c5de07a7d2
  ms.sourcegitcommit: 7de323416e472639edcff135bfc7d47bd5715256
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/11/2018
  ms.locfileid: "44370525"
durationInMinutes: 10
content: '[!include[](includes/4-cloud-deployment-models.md)]'
