### YamlMime:ModuleUnit
uid: learn.principles-cloud-computing.4-cloud-deployment-models
title: 클라우드 배포 모델
metadata:
  title: 클라우드 배포 모델
  description: 클라우드 배포 모델
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 10
content: |
  [!include[](includes/4-cloud-deployment-models.md)]