### YamlMime:ModuleUnit
uid: learn.create-azure-storage-account.3-choose-your-account-settings
title: 계정 설정 선택
metadata:
  title: 계정 설정 선택
  description: 계정 설정 선택
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 7
content: |
  [!include[](includes/3-choose-your-account-settings.md)]