### YamlMime:ModuleUnit
uid: learn.create-azure-storage-account.3-choose-your-account-settings
title: 계정 설정 선택
metadata:
  title: 계정 설정 선택
  description: 계정 설정 선택
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 86463780f25a2aa164342d6539d35ec5586984af
  ms.sourcegitcommit: b21a4b22de591cfa776684ba2eab9ba27248c65d
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/19/2018
  ms.locfileid: "46354078"
durationInMinutes: 5
content: '[!include[](includes/3-choose-your-account-settings.md)]'
