### YamlMime:ModuleUnit
uid: learn.create-azure-storage-account.3-choose-your-account-settings
title: 계정 설정 선택
metadata:
  title: 계정 설정 선택
  description: 계정 설정 선택
  ms.openlocfilehash: 2b4b0b6fa5cf2ea927065e28f0e634d4719a5c8b
  ms.sourcegitcommit: c07e11980180ae35cb3485548f81e16152d77781
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/02/2018
  ms.locfileid: "43471796"
durationInMinutes: 7
content: '[!include[](includes/3-choose-your-account-settings.md)]'
