### YamlMime:ModuleUnit
uid: learn.scale-and-size-virtual-machines.5-exercise-create-a-scale-set-and-configure-autoscaling
title: <span data-ttu-id="f7eb7-101">연습 - 확장 집합 만들기 및 자동 크기 조정 구성</span><span class="sxs-lookup"><span data-stu-id="f7eb7-101">Exercise - Create a scale set and configure autoscaling</span></span>
metadata:
  title: <span data-ttu-id="f7eb7-102">연습 - 확장 집합 만들기 및 자동 크기 조정 구성</span><span class="sxs-lookup"><span data-stu-id="f7eb7-102">Exercise - Create a scale set and configure autoscaling</span></span>
  description: <span data-ttu-id="f7eb7-103">연습 - 확장 집합 만들기 및 자동 크기 조정 구성</span><span class="sxs-lookup"><span data-stu-id="f7eb7-103">Exercise - Create a scale set and configure autoscaling</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 5cf3cb0d1bbc8fa928f722f9b0cead96a1aabc68
  ms.sourcegitcommit: 87602488fb13c785daee0e5831ace59668a85d52
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/18/2018
  ms.locfileid: "45992306"
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-a-scale-set-and-configure-autoscaling.md)]'
