### YamlMime:ModuleUnit
uid: learn.scale-and-size-virtual-machines.5-exercise-create-a-scale-set-and-configure-autoscaling
title: 연습 - 확장 집합 만들기 및 자동 크기 조정 구성
metadata:
  title: 연습 - 확장 집합 만들기 및 자동 크기 조정 구성
  description: 연습 - 확장 집합 만들기 및 자동 크기 조정 구성
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: a0c8a51ea1f53b0ad09a2e6e1ee76cd7bbebc9a6
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47145405"
azureSandbox: true
durationInMinutes: 20
content: '[!include[](includes/5-exercise-create-a-scale-set-and-configure-autoscaling.md)]'
