### YamlMime:ModuleUnit
uid: learn.enable-reliable-messaging-for-big-data-applications-using-azure-event-hubs.5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub
title: <span data-ttu-id="32388-101">연습 - Event Hub를 통해 메시지를 보내거나 받도록 응용 프로그램 구성</span><span class="sxs-lookup"><span data-stu-id="32388-101">Exercise - Configure applications to send or receive messages through an Event Hub</span></span>
metadata:
  title: <span data-ttu-id="32388-102">연습 - Event Hub를 통해 메시지를 보내거나 받도록 응용 프로그램 구성</span><span class="sxs-lookup"><span data-stu-id="32388-102">Exercise - Configure applications to send or receive messages through an Event Hub</span></span>
  description: <span data-ttu-id="32388-103">Event Hub를 통해 메시지를 보내거나 받도록 응용 프로그램 구성</span><span class="sxs-lookup"><span data-stu-id="32388-103">Configure applications to send or receive messages through an Event Hub</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: e80e64b5b76a501e334bb018a08e9e9e30b17bc9
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44248302"
durationInMinutes: 10
content: '[!include[](includes/5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub.md)]'
