### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.3-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal
title: <span data-ttu-id="63a3c-101">Azure Portal을 사용하여 Azure VM 디스크 캐시 사용 및 구성</span><span class="sxs-lookup"><span data-stu-id="63a3c-101">Enable and configure Azure VM disk cache with the Azure portal</span></span>
metadata:
  title: <span data-ttu-id="63a3c-102">Azure Portal을 사용하여 Azure VM 디스크 캐시 사용 및 구성</span><span class="sxs-lookup"><span data-stu-id="63a3c-102">Enable and configure Azure VM disk cache with the Azure portal</span></span>
  description: <span data-ttu-id="63a3c-103">Azure Portal을 사용하여 Azure VM 디스크 캐시 사용 및 구성</span><span class="sxs-lookup"><span data-stu-id="63a3c-103">Enable and configure Azure VM disk cache with the Azure portal</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 20238bbb5638ea2e5985a7a51e5885700f64099b
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47141230"
durationInMinutes: 5
content: <span data-ttu-id="63a3c-104">[!include[](includes/3-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal.md)</span><span class="sxs-lookup"><span data-stu-id="63a3c-104">[!include[](includes/3-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal.md)</span></span>
