### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.5-manage-cache-settings-with-powershell
title: <span data-ttu-id="f7110-101">PowerShell을 사용하여 캐시 설정 관리</span><span class="sxs-lookup"><span data-stu-id="f7110-101">Manage cache settings with PowerShell</span></span>
metadata:
  title: <span data-ttu-id="f7110-102">PowerShell을 사용하여 캐시 설정 관리</span><span class="sxs-lookup"><span data-stu-id="f7110-102">Manage cache settings with PowerShell</span></span>
  description: <span data-ttu-id="f7110-103">PowerShell을 사용하여 캐시 설정 관리</span><span class="sxs-lookup"><span data-stu-id="f7110-103">Manage cache settings with PowerShell</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: b862288f8868319d3a3e0c681632987fbc6419ac
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47131803"
durationInMinutes: 5
content: '[!include[](includes/5-manage-cache-settings-with-powershell.md)]'
