### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.6-exercise-manage-cache-settings-with-powershell
title: <span data-ttu-id="89475-101">연습 - PowerShell을 사용하여 캐시 설정 관리</span><span class="sxs-lookup"><span data-stu-id="89475-101">Exercise - Manage cache settings with PowerShell</span></span>
metadata:
  title: <span data-ttu-id="89475-102">연습 - PowerShell을 사용하여 캐시 설정 관리</span><span class="sxs-lookup"><span data-stu-id="89475-102">Exercise - Manage cache settings with PowerShell</span></span>
  description: <span data-ttu-id="89475-103">연습 - PowerShell을 사용하여 캐시 설정 관리</span><span class="sxs-lookup"><span data-stu-id="89475-103">Exercise - Manage cache settings with PowerShell</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 9ef6bdfc2fd168245857ba74e86667e790bb4e0b
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44231234"
durationInMinutes: 10
content: '[!include[](includes/6-exercise-manage-cache-settings-with-powershell.md)]'
