### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.6-exercise-manage-cache-settings-with-powershell
title: <span data-ttu-id="bf2fb-101">연습 - PowerShell을 사용하여 캐시 설정 관리</span><span class="sxs-lookup"><span data-stu-id="bf2fb-101">Exercise - Manage cache settings with PowerShell</span></span>
metadata:
  title: <span data-ttu-id="bf2fb-102">연습 - PowerShell을 사용하여 캐시 설정 관리</span><span class="sxs-lookup"><span data-stu-id="bf2fb-102">Exercise - Manage cache settings with PowerShell</span></span>
  description: <span data-ttu-id="bf2fb-103">연습 - PowerShell을 사용하여 캐시 설정 관리</span><span class="sxs-lookup"><span data-stu-id="bf2fb-103">Exercise - Manage cache settings with PowerShell</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 7bb787e2ea32d2ccc5a912c10d2a7c348b656633
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47146761"
interactive: powershell
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/6-exercise-manage-cache-settings-with-powershell.md)]'
