### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.3-connect-your-application-to-simulator
title: <span data-ttu-id="957f0-101">커피 머신 시뮬레이터에 응용 프로그램 연결</span><span class="sxs-lookup"><span data-stu-id="957f0-101">Connect your application to the coffee machine simulator</span></span>
metadata:
  title: <span data-ttu-id="957f0-102">커피 머신 시뮬레이터에 응용 프로그램 연결</span><span class="sxs-lookup"><span data-stu-id="957f0-102">Connect your application to the coffee machine simulator</span></span>
  description: <span data-ttu-id="957f0-103">커피 머신 시뮬레이터에 응용 프로그램 연결</span><span class="sxs-lookup"><span data-stu-id="957f0-103">Connect your application to coffee machine simulator</span></span>
  ms.openlocfilehash: d7dbbf8226940d5a61ee707edd7600b0bfd0bf2e
  ms.sourcegitcommit: b97ed72bd7e3fb77b49de71e8ef35d3f70dfd636
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43795031"
durationInMinutes: 12
content: '[!include[](includes/3-connect-your-application-to-simulator.md)]'
