### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.5-configure-rules-and-actions
title: 커피 머신을 모니터링하는 규칙과 작업 구성
metadata:
  title: 커피 머신을 모니터링하는 규칙과 작업 구성
  description: 커피 머신을 모니터링하는 규칙과 작업 구성
  ms.openlocfilehash: b88da62e3fbf019371ec59a009d2a52e3ced1b75
  ms.sourcegitcommit: b97ed72bd7e3fb77b49de71e8ef35d3f70dfd636
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43795731"
durationInMinutes: 12
content: '[!include[](includes/5-configure-rules-and-actions.md)]'
