### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.10-exercise-connect-with-your-azure-storage-configuration
title: Azure Storage 구성에 연결
metadata:
  title: Azure Storage 구성에 연결
  description: Azure Storage 구성에 연결
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  zone_pivot_groups: dev-lang-csharp-javascript
  ms.openlocfilehash: fc60b9e975dbd76fa90a087eeb19494805683edf
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44239326"
interactive: bash-editor
durationInMinutes: 15
content: '[!include[](includes/10-exercise-connect-with-your-azure-storage-configuration.md)]'
