### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.7-exercise-add-azure-storage-configuration-to-your-app
title: 연습 - 앱에 Azure Storage 구성 추가
metadata:
  title: 연습 - 앱에 Azure Storage 구성 추가
  description: 연습 - 앱에 Azure Storage 구성 추가
  ms.openlocfilehash: 81492226750978399fb2a82fb32c14b5ddefb08d
  ms.sourcegitcommit: 107578417899e44b5611917dec7bcc21d4c1582e
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 08/29/2018
  ms.locfileid: "43229023"
durationInMinutes: 10
content: '[!include[](includes/7-exercise-add-azure-storage-configuration-to-your-app.md)]'
