### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.7-exercise-add-azure-storage-configuration-to-your-app
title: <span data-ttu-id="e2753-101">연습 - 앱에 Azure Storage 구성 추가</span><span class="sxs-lookup"><span data-stu-id="e2753-101">Exercise - Add Azure Storage configuration to your app</span></span>
metadata:
  title: <span data-ttu-id="e2753-102">연습 - 앱에 Azure Storage 구성 추가</span><span class="sxs-lookup"><span data-stu-id="e2753-102">Exercise - Add Azure Storage configuration to your app</span></span>
  description: <span data-ttu-id="e2753-103">연습 - 앱에 Azure Storage 구성 추가</span><span class="sxs-lookup"><span data-stu-id="e2753-103">Exercise - Add Azure Storage configuration to your app</span></span>
  ms.openlocfilehash: 81492226750978399fb2a82fb32c14b5ddefb08d
  ms.sourcegitcommit: 107578417899e44b5611917dec7bcc21d4c1582e
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 08/29/2018
  ms.locfileid: "43229023"
durationInMinutes: 10
content: '[!include[](includes/7-exercise-add-azure-storage-configuration-to-your-app.md)]'
