### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.9-exercise-connect-with-your-azure-storage-configuration
title: <span data-ttu-id="301a0-101">Azure Storage 구성에 연결</span><span class="sxs-lookup"><span data-stu-id="301a0-101">Connect with your Azure Storage configuration</span></span>
metadata:
  title: <span data-ttu-id="301a0-102">Azure Storage 구성에 연결</span><span class="sxs-lookup"><span data-stu-id="301a0-102">Connect with your Azure Storage configuration</span></span>
  description: <span data-ttu-id="301a0-103">Azure Storage 구성에 연결</span><span class="sxs-lookup"><span data-stu-id="301a0-103">Connect with your Azure Storage configuration</span></span>
  ms.openlocfilehash: d7b2a71726a5830927bb64e8d4008c9f9df291f4
  ms.sourcegitcommit: b97ed72bd7e3fb77b49de71e8ef35d3f70dfd636
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43792752"
durationInMinutes: 10
content: '[!include[](includes/9-exercise-connect-with-your-azure-storage-configuration.md)]'
