### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.9-exercise-connect-with-your-azure-storage-configuration
title: Azure Storage 구성에 연결
metadata:
  title: Azure Storage 구성에 연결
  description: Azure Storage 구성에 연결
  ms.openlocfilehash: d7b2a71726a5830927bb64e8d4008c9f9df291f4
  ms.sourcegitcommit: b97ed72bd7e3fb77b49de71e8ef35d3f70dfd636
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43792752"
durationInMinutes: 10
content: '[!include[](includes/9-exercise-connect-with-your-azure-storage-configuration.md)]'
