### YamlMime:ModuleUnit
uid: learn.manage-secrets-with-azure-key-vault.6-configure-deploy-run-azure
title: <span data-ttu-id="3c930-101">Azure에서 구성, 배포 및 실행</span><span class="sxs-lookup"><span data-stu-id="3c930-101">Configure, deploy, and run in Azure</span></span>
metadata:
  title: <span data-ttu-id="3c930-102">Azure에서 구성, 배포 및 실행</span><span class="sxs-lookup"><span data-stu-id="3c930-102">Configure, deploy, and run in Azure</span></span>
  description: <span data-ttu-id="3c930-103">Azure에서 구성, 배포 및 실행</span><span class="sxs-lookup"><span data-stu-id="3c930-103">Configure, deploy, and run in Azure</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: c821587b542dde7521edab678b43097232763181
  ms.sourcegitcommit: b6f5aa15bae13cb0f53667fba1d404b7bec76f67
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/17/2018
  ms.locfileid: "45760219"
durationInMinutes: 12
interactive: bash
azureSandbox: true
content: '[!include[](includes/6-configure-deploy-run-azure.md)]'
