### YamlMime:ModuleUnit
uid: learn.manage-secrets-with-azure-key-vault.6-configure-deploy-run-azure
title: <span data-ttu-id="c1f09-101">Azure에서 구성, 배포 및 실행</span><span class="sxs-lookup"><span data-stu-id="c1f09-101">Configure, deploy, and run in Azure</span></span>
metadata:
  title: <span data-ttu-id="c1f09-102">Azure에서 구성, 배포 및 실행</span><span class="sxs-lookup"><span data-stu-id="c1f09-102">Configure, deploy, and run in Azure</span></span>
  description: <span data-ttu-id="c1f09-103">Azure에서 구성, 배포 및 실행</span><span class="sxs-lookup"><span data-stu-id="c1f09-103">Configure, deploy, and run in Azure</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: c821587b542dde7521edab678b43097232763181
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47131754"
durationInMinutes: 12
interactive: bash
azureSandbox: true
content: '[!include[](includes/6-configure-deploy-run-azure.md)]'
