### YamlMime:ModuleUnit
uid: learn.intro-to-containers.2-configure-local
metadata:
  title: 로컬 컨테이너 개발 환경 구성
  description: 로컬 컨테이너 개발 환경을 구성합니다.
  ms.openlocfilehash: f33047eb1295ea2dd44904a8e2ddb1d78b413682
  ms.sourcegitcommit: 56db32ad6f98b7d769f2b1201825d4f6d9b7362d
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43727906"
title: 로컬 컨테이너 개발 환경 구성
durationInMinutes: 10
content: '[!include[](includes/2-configure-local.md)]'
