### YamlMime:ModuleUnit
uid: learn.intro-to-containers.2-configure-local
metadata:
  title: <span data-ttu-id="aec22-101">로컬 컨테이너 개발 환경 구성</span><span class="sxs-lookup"><span data-stu-id="aec22-101">Configure a local container development environment</span></span>
  description: <span data-ttu-id="aec22-102">로컬 컨테이너 개발 환경을 구성합니다.</span><span class="sxs-lookup"><span data-stu-id="aec22-102">Configure a local container development environment.</span></span>
  ms.openlocfilehash: f33047eb1295ea2dd44904a8e2ddb1d78b413682
  ms.sourcegitcommit: 56db32ad6f98b7d769f2b1201825d4f6d9b7362d
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43727906"
title: <span data-ttu-id="aec22-103">로컬 컨테이너 개발 환경 구성</span><span class="sxs-lookup"><span data-stu-id="aec22-103">Configure a local container development environment</span></span>
durationInMinutes: 10
content: '[!include[](includes/2-configure-local.md)]'
