### YamlMime:ModuleUnit
uid: learn.intro-to-containers.2-configure-local
metadata:
  title: <span data-ttu-id="14d53-101">로컬 컨테이너 개발 환경 구성</span><span class="sxs-lookup"><span data-stu-id="14d53-101">Configure a local container development environment</span></span>
  description: <span data-ttu-id="14d53-102">로컬 컨테이너 개발 환경을 구성합니다.</span><span class="sxs-lookup"><span data-stu-id="14d53-102">Configure a local container development environment.</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 365b86322b9585abcedd1a61fdcf91840bae48bf
  ms.sourcegitcommit: b6f5aa15bae13cb0f53667fba1d404b7bec76f67
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/17/2018
  ms.locfileid: "45758628"
title: <span data-ttu-id="14d53-103">로컬 컨테이너 개발 환경 구성</span><span class="sxs-lookup"><span data-stu-id="14d53-103">Configure a local container development environment</span></span>
durationInMinutes: 10
content: '[!include[](includes/2-configure-local.md)]'
