### YamlMime:ModuleUnit
uid: learn.design-for-performance-and-scalability.5-identify-performance-bottlenecks-in-your-application
title: <span data-ttu-id="09d24-101">응용 프로그램에서 성능 병목 상태 식별</span><span class="sxs-lookup"><span data-stu-id="09d24-101">Identify performance bottlenecks in your application</span></span>
metadata:
  title: <span data-ttu-id="09d24-102">응용 프로그램에서 성능 병목 상태 식별</span><span class="sxs-lookup"><span data-stu-id="09d24-102">Identify performance bottlenecks in your application</span></span>
  description: <span data-ttu-id="09d24-103">이 단원에서는 응용 프로그램에서 성능 병목 상태를 식별하는 방법을 알아보겠습니다.</span><span class="sxs-lookup"><span data-stu-id="09d24-103">In this unit we'll discuss how to identify performance bottlenecks in your application</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: c7d8f1f8564a139f58fb17efc300af92e96cf906
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47143131"
durationInMinutes: 9
content: >
  [!include[](includes/5-identify-performance-bottlenecks-in-your-application.md)]
quiz:
  title: <span data-ttu-id="09d24-104">지식 점검</span><span class="sxs-lookup"><span data-stu-id="09d24-104">Check your knowledge</span></span>
  questions:
  - content: <span data-ttu-id="09d24-105">다음 중 Application Insights를 가장 잘 나타낸 설명은 어느 것인가요?</span><span class="sxs-lookup"><span data-stu-id="09d24-105">Which of the following best describes Application Insights?</span></span>
    choices:
    - content: <span data-ttu-id="09d24-106">Azure에서 모든 모니터링 요구 사항에 대한 단일 보기</span><span class="sxs-lookup"><span data-stu-id="09d24-106">A single view for all your monitoring needs in Azure</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="09d24-107">Application Insights는 응용 프로그램 성능에 대한 풍부한 데이터를 제공할 수 있지만 포괄적인 Azure 모니터링 솔루션이 아닙니다.</span><span class="sxs-lookup"><span data-stu-id="09d24-107">While Application Insights can provide a wealth of data on your application performance, is it not a comprehensive Azure monitoring solution.</span></span>
    - content: <span data-ttu-id="09d24-108">상태 엔드포인트 모니터링 패턴 구현</span><span class="sxs-lookup"><span data-stu-id="09d24-108">An implementation of the health endpoint monitoring pattern</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="09d24-109">상태 엔드포인트 모니터링 패턴은 전반적인 상태에 대해 응용 프로그램에서 노출된 모니터링 엔드포인트에 중점을 둡니다.</span><span class="sxs-lookup"><span data-stu-id="09d24-109">The health endpoint monitoring pattern focuses on monitoring endpoints exposed by your application for overall health.</span></span>
    - content: <span data-ttu-id="09d24-110">인프라 및 응용 프로그램에서 로그 컬렉션을 사용한 작업 영역</span><span class="sxs-lookup"><span data-stu-id="09d24-110">A workspace to enable collection of logs across infrastructure and applications</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="09d24-111">Log Analytics는 인프라 및 응용 프로그램에서 로그 컬렉션을 사용할 수 있는 작업 영역입니다.</span><span class="sxs-lookup"><span data-stu-id="09d24-111">Log Analytics is a workspace that enables the collection of logs across infrastructure and applications.</span></span>
    - content: <span data-ttu-id="09d24-112">웹 응용 프로그램의 가용성, 성능 및 사용량을 모니터링하는 서비스</span><span class="sxs-lookup"><span data-stu-id="09d24-112">A service to monitor availability, performance, and usage of web applications</span></span>
      isCorrect: true
      correctExplanation: <span data-ttu-id="09d24-113">Application Insights는 웹 응용 프로그램의 가용성, 성능 및 사용량을 모니터링하는 서비스입니다.</span><span class="sxs-lookup"><span data-stu-id="09d24-113">Application Insights is a service to monitor availability, performance, and usage of web applications.</span></span>
  - content: '<span data-ttu-id="09d24-114">True 또는 false: Log Analytics는 사용자 지정 로그 및 메트릭을 추적합니다.</span><span class="sxs-lookup"><span data-stu-id="09d24-114">True or false: Log Analytics tracks custom logs and metrics.</span></span>'
    choices:
    - content: <span data-ttu-id="09d24-115">True</span><span class="sxs-lookup"><span data-stu-id="09d24-115">True</span></span>
      isCorrect: true
      correctExplanation: <span data-ttu-id="09d24-116">사용자 지정 로그 및 메트릭의 경우 HTTP 데이터 수집기 API를 사용하여 REST API 클라이언트에서 Log Analytics에 데이터를 작성하거나 Azure Logic App을 사용하여 사용자 지정 워크플로에서 데이터를 작성할 수 있습니다.</span><span class="sxs-lookup"><span data-stu-id="09d24-116">For custom logs and metrics, you can use the HTTP Data Collector API to write data to Log Analytics from any REST API client or an Azure Logic App to write data from a custom workflow.</span></span>
    - content: <span data-ttu-id="09d24-117">False</span><span class="sxs-lookup"><span data-stu-id="09d24-117">False</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="09d24-118">사용자 지정 로그 및 메트릭의 경우 HTTP 데이터 수집기 API를 사용하여 REST API 클라이언트에서 Log Analytics에 데이터를 작성하거나 Azure Logic App을 사용하여 사용자 지정 워크플로에서 데이터를 작성할 수 있습니다.</span><span class="sxs-lookup"><span data-stu-id="09d24-118">For custom logs and metrics, you can use the HTTP Data Collector API to write data to Log Analytics from any REST API client or an Azure Logic App to write data from a custom workflow.</span></span>
