### YamlMime:ModuleUnit
uid: learn.design-for-performance-and-scalability.5-identify-performance-bottlenecks-in-your-application
title: <span data-ttu-id="5184c-101">응용 프로그램에서 성능 병목 상태 식별</span><span class="sxs-lookup"><span data-stu-id="5184c-101">Identify performance bottlenecks in your application</span></span>
metadata:
  title: <span data-ttu-id="5184c-102">응용 프로그램에서 성능 병목 상태 식별</span><span class="sxs-lookup"><span data-stu-id="5184c-102">Identify performance bottlenecks in your application</span></span>
  description: <span data-ttu-id="5184c-103">이 단원에서는 응용 프로그램에서 성능 병목 상태를 식별하는 방법을 알아보겠습니다.</span><span class="sxs-lookup"><span data-stu-id="5184c-103">In this unit we'll discuss how to identify performance bottlenecks in your application</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: a01a564ec53bf55924adfb91fcf79031bc2396f7
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44240210"
durationInMinutes: 5
content: >
  [!include[](includes/5-identify-performance-bottlenecks-in-your-application.md)]
quiz:
  title: <span data-ttu-id="5184c-104">지식 검사 - 응용 프로그램에서 성능 병목 상태 식별</span><span class="sxs-lookup"><span data-stu-id="5184c-104">Knowledge Check - Identify performance bottlenecks in your application</span></span>
  questions:
  - content: <span data-ttu-id="5184c-105">다음 중 Application Insights를 가장 잘 나타낸 설명은 어느 것인가요?</span><span class="sxs-lookup"><span data-stu-id="5184c-105">Which of the following best describes Application Insights?</span></span>
    choices:
    - content: <span data-ttu-id="5184c-106">Azure의 모니터링 요구를 위한 단일 창</span><span class="sxs-lookup"><span data-stu-id="5184c-106">A single pane of glass for our monitoring needs in Azure</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="5184c-107">Application Insights는 응용 프로그램 성능에 대한 풍부한 데이터를 제공할 수 있지만 포괄적인 Azure 모니터링 솔루션이 아닙니다.</span><span class="sxs-lookup"><span data-stu-id="5184c-107">While Application Insights can provide a wealth of data on your application performance, is it not a comprehensive Azure monitoring solution.</span></span>
    - content: <span data-ttu-id="5184c-108">상태 엔드포인트 모니터링 패턴 구현</span><span class="sxs-lookup"><span data-stu-id="5184c-108">An implementation of the health endpoint monitoring pattern</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="5184c-109">상태 엔드포인트 모니터링 패턴은 전반적인 상태에 대해 응용 프로그램에서 노출된 모니터링 엔드포인트에 중점을 둡니다.</span><span class="sxs-lookup"><span data-stu-id="5184c-109">The health endpoint monitoring pattern focuses on monitoring endpoints exposed by your application for overall health.</span></span>
    - content: <span data-ttu-id="5184c-110">인프라 및 응용 프로그램에서 로그 수집이 가능한 작업 영역</span><span class="sxs-lookup"><span data-stu-id="5184c-110">A workspace to enable collection of logs across infrastructure and applications</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="5184c-111">Log Analytics는 인프라 및 응용 프로그램에서 로그를 수집할 수 있는 작업 영역입니다.</span><span class="sxs-lookup"><span data-stu-id="5184c-111">Log Analytics is a workspace that enables the collection of logs across infrastructure and applictions.</span></span>
    - content: <span data-ttu-id="5184c-112">웹 응용 프로그램의 가용성, 성능 및 사용 현황을 모니터하는 서비스</span><span class="sxs-lookup"><span data-stu-id="5184c-112">A service to monitor availability, performance, and usage of web applications</span></span>
      isCorrect: true
      correctExplanation: <span data-ttu-id="5184c-113">Application Insights는 웹 응용 프로그램의 가용성, 성능 및 사용량을 모니터링하는 서비스입니다.</span><span class="sxs-lookup"><span data-stu-id="5184c-113">Application Insights is a service to monitor availability, performance, and usage of web applications.</span></span>
  - content: <span data-ttu-id="5184c-114">Log Analytics를 사용하여 사용자 지정 로그 및 메트릭을 추적할 수 있습니다.</span><span class="sxs-lookup"><span data-stu-id="5184c-114">You can use Log Analytics to track custom logs and metrics.</span></span>
    choices:
    - content: <span data-ttu-id="5184c-115">True</span><span class="sxs-lookup"><span data-stu-id="5184c-115">True</span></span>
      isCorrect: true
      correctExplanation: <span data-ttu-id="5184c-116">사용자 지정 로그 및 메트릭의 경우 HTTP 데이터 수집기 API를 사용하여 REST API 클라이언트에서 Log Analytics에 데이터를 작성하거나 Azure Logic App을 사용하여 사용자 지정 워크플로에서 데이터를 작성할 수 있습니다.</span><span class="sxs-lookup"><span data-stu-id="5184c-116">For custom logs and metrics, you can use the HTTP Data Collector API to write data to Log Analytics from any REST API client or an Azure Logic App to write data from a custom workflow.</span></span>
    - content: <span data-ttu-id="5184c-117">False</span><span class="sxs-lookup"><span data-stu-id="5184c-117">False</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="5184c-118">사용자 지정 로그 및 메트릭의 경우 HTTP 데이터 수집기 API를 사용하여 REST API 클라이언트에서 Log Analytics에 데이터를 작성하거나 Azure Logic App을 사용하여 사용자 지정 워크플로에서 데이터를 작성할 수 있습니다.</span><span class="sxs-lookup"><span data-stu-id="5184c-118">For custom logs and metrics, you can use the HTTP Data Collector API to write data to Log Analytics from any REST API client or an Azure Logic App to write data from a custom workflow.</span></span>
