### YamlMime:ModuleUnit
uid: learn.introduction-to-security.5-network-security
title: 네트워크 보호
metadata:
  title: 네트워크 보호
  description: 이 단원에서는 네트워크 인프라를 보호하는 방법에 대해 알아보겠습니다.
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 434584c1861f5b8031069c787b878c654a8ba848
  ms.sourcegitcommit: b21a4b22de591cfa776684ba2eab9ba27248c65d
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/19/2018
  ms.locfileid: "46352758"
durationInMinutes: 5
content: '[!include[](includes/5-network-security.md)]'
