### YamlMime:ModuleUnit
uid: learn.introduction-to-security.5-network-security
title: <span data-ttu-id="2f3fd-101">네트워크 보호</span><span class="sxs-lookup"><span data-stu-id="2f3fd-101">Protect your network</span></span>
metadata:
  title: <span data-ttu-id="2f3fd-102">네트워크 보호</span><span class="sxs-lookup"><span data-stu-id="2f3fd-102">Protect your network</span></span>
  description: <span data-ttu-id="2f3fd-103">이 단원에서는 네트워크 인프라를 보호하는 방법에 대해 알아보겠습니다.</span><span class="sxs-lookup"><span data-stu-id="2f3fd-103">In this unit we'll discuss how to secure your network infrastructure</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 9e292fa70474a3250e8b53689a2bedaaf261ea96
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44246126"
durationInMinutes: 5
content: '[!include[](includes/5-network-security.md)]'
