### YamlMime:ModuleUnit
uid: learn.introduction-to-security.5-network-security
title: 네트워크 보호
metadata:
  title: 네트워크 보호
  description: 이 단위 네트워크 인프라를 보호 하는 방법을 살펴보겠습니다.
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 5
content: |
  [!include[](includes/5-network-security.md)]