### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-web-apps.5-exercise-create-an-asp.net-core-web-application-on-linux
title: <span data-ttu-id="4c222-101">연습 - Linux에서 ASP.NET Core 응용 프로그램 만들기</span><span class="sxs-lookup"><span data-stu-id="4c222-101">Exercise - Create an ASP.NET Core application on Linux</span></span>
metadata:
  title: <span data-ttu-id="4c222-102">연습 - Linux에서 ASP.NET Core 응용 프로그램 만들기</span><span class="sxs-lookup"><span data-stu-id="4c222-102">Exercise - Create an ASP.NET Core application on Linux</span></span>
  description: <span data-ttu-id="4c222-103">연습 - Linux에서 ASP.NET Core 응용 프로그램 만들기</span><span class="sxs-lookup"><span data-stu-id="4c222-103">Exercise - Create an ASP.NET Core application on Linux</span></span>
  ms.openlocfilehash: 1205619f0129555a08587fa142627e6d917e3fcb
  ms.sourcegitcommit: 7cb102aab9e02ef52429d61a119a574c7ad3b2fb
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43725514"
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-an-asp.net-core-web-application-on-linux.md)]'
