### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-web-apps.5-exercise-create-an-asp.net-core-web-application-on-linux
title: 연습 - Linux에서 ASP.NET Core 응용 프로그램 만들기
metadata:
  title: 연습 - Linux에서 ASP.NET Core 응용 프로그램 만들기
  description: 연습 - Linux에서 ASP.NET Core 응용 프로그램 만들기
  ms.openlocfilehash: 1205619f0129555a08587fa142627e6d917e3fcb
  ms.sourcegitcommit: a8497a897faccb27bfeaf5812a5887ac15f97625
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 08/24/2018
  ms.locfileid: "42821640"
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-an-asp.net-core-web-application-on-linux.md)]'
