### YamlMime:ModuleUnit
uid: learn.interactive-deep-learning.4-configure-dsvm
title: <span data-ttu-id="24d68-101">DSVM 구성</span><span class="sxs-lookup"><span data-stu-id="24d68-101">Configure DSVM</span></span>
metadata:
  title: <span data-ttu-id="24d68-102">심층 학습용 Data Science Virtual Machine 구성</span><span class="sxs-lookup"><span data-stu-id="24d68-102">Configure the Data Science Virtual Machine for Deep Learning</span></span>
  description: <span data-ttu-id="24d68-103">심층 학습용 Data Science Virtual Machine 구성</span><span class="sxs-lookup"><span data-stu-id="24d68-103">Configure the Data Science Virtual Machine for Deep Learning</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 817429ab3de31e91be6c9d471a03a8f9c0f0ec85
  ms.sourcegitcommit: 1c45ea8b740761474e8cb320f14c88ae71a13261
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/11/2018
  ms.locfileid: "44383636"
labId: 45998
interactive: bash
azureSandbox: true
durationInMinutes: 30
content: '[!include[](includes/4-configure-dsvm.md)]'
