### YamlMime:ModuleUnit
uid: learn.interactive-deep-learning.4-configure-dsvm
title: DSVM 구성
metadata:
  title: 심층 학습용 Data Science Virtual Machine 구성
  description: 심층 학습용 Data Science Virtual Machine 구성
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 817429ab3de31e91be6c9d471a03a8f9c0f0ec85
  ms.sourcegitcommit: 1c45ea8b740761474e8cb320f14c88ae71a13261
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/11/2018
  ms.locfileid: "44383636"
labId: 45998
interactive: bash
azureSandbox: true
durationInMinutes: 30
content: '[!include[](includes/4-configure-dsvm.md)]'
