### YamlMime:ModuleUnit
uid: learn.interactive-deep-learning.4-configure-dsvm
title: <span data-ttu-id="925cf-101">DSVM 구성</span><span class="sxs-lookup"><span data-stu-id="925cf-101">Configure DSVM</span></span>
metadata:
  title: <span data-ttu-id="925cf-102">심층 학습용 Data Science Virtual Machine 구성</span><span class="sxs-lookup"><span data-stu-id="925cf-102">Configure the Data Science Virtual Machine for Deep Learning</span></span>
  description: <span data-ttu-id="925cf-103">심층 학습용 Data Science Virtual Machine 구성</span><span class="sxs-lookup"><span data-stu-id="925cf-103">Configure the Data Science Virtual Machine for Deep Learning</span></span>
  ms.openlocfilehash: 54f188e18c055a9d80f3a71bf482a781b723b1e2
  ms.sourcegitcommit: 314b617e66d461bd6bf5aa076aacdc150b773606
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/06/2018
  ms.locfileid: "43833169"
interactive: bash
durationInMinutes: 30
content: '[!include[](includes/4-configure-dsvm.md)]'
