### YamlMime:ModuleUnit
uid: learn.run-docker-containers-aci.4-use-environment-variables
metadata:
  title: <span data-ttu-id="b3d3a-101">환경 변수 설정</span><span class="sxs-lookup"><span data-stu-id="b3d3a-101">Set environment variables</span></span>
  description: <span data-ttu-id="b3d3a-102">Azure Container Instances에서 환경 변수를 설정합니다.</span><span class="sxs-lookup"><span data-stu-id="b3d3a-102">Set environment variables in Azure Container Instances.</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 121d22c224c33875cf10038d9c63596882a3b1f4
  ms.sourcegitcommit: b6f5aa15bae13cb0f53667fba1d404b7bec76f67
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/17/2018
  ms.locfileid: "45760746"
title: <span data-ttu-id="b3d3a-103">환경 변수 설정</span><span class="sxs-lookup"><span data-stu-id="b3d3a-103">Set environment variables</span></span>
interactive: bash
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/4-use-environment-variables.md)]'
