### YamlMime:ModuleUnit
uid: learn.run-docker-containers-aci.4-use-environment-variables
metadata:
  title: <span data-ttu-id="6811a-101">환경 변수 설정</span><span class="sxs-lookup"><span data-stu-id="6811a-101">Set environment variables</span></span>
  description: <span data-ttu-id="6811a-102">Azure Container Instances에서 환경 변수 설정</span><span class="sxs-lookup"><span data-stu-id="6811a-102">Set environment variables in Azure Container Instances.</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 121d22c224c33875cf10038d9c63596882a3b1f4
  ms.sourcegitcommit: 8213d1af6ad9da967a5e195f0b40b00265cb192c
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/10/2018
  ms.locfileid: "44308218"
title: <span data-ttu-id="6811a-103">환경 변수 설정</span><span class="sxs-lookup"><span data-stu-id="6811a-103">Set environment variables</span></span>
interactive: bash
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/4-use-environment-variables.md)]'
