### YamlMime:ModuleUnit
uid: learn.run-docker-containers-aci.4-use-environment-variables
interactive: bash
metadata:
  title: 환경 변수 설정
  description: Azure Container Instances에서 환경 변수 설정
  ms.openlocfilehash: 921168a568e52b47ff347521fff4969213d0fa88
  ms.sourcegitcommit: 314b617e66d461bd6bf5aa076aacdc150b773606
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/06/2018
  ms.locfileid: "43833788"
title: 환경 변수 설정
durationInMinutes: 10
content: '[!include[](includes/4-use-environment-variables.md)]'
