### YamlMime:ModuleUnit
uid: learn.design-for-security.6-network-security
title: <span data-ttu-id="7c28b-101">네트워크 보안</span><span class="sxs-lookup"><span data-stu-id="7c28b-101">Network security</span></span>
metadata:
  title: <span data-ttu-id="7c28b-102">네트워크 보안</span><span class="sxs-lookup"><span data-stu-id="7c28b-102">Network security</span></span>
  description: <span data-ttu-id="7c28b-103">이 단원에서는 네트워크 인프라를 보호하는 방법에 대해 알아보겠습니다.</span><span class="sxs-lookup"><span data-stu-id="7c28b-103">In this unit we'll discuss how to secure your network infrastructure</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: cc35a096e064136f7d56fc05c4ce856fd1918641
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47142395"
durationInMinutes: 10
content: >
  [!include[](includes/6-network-security.md)]
quiz:
  title: <span data-ttu-id="7c28b-104">지식 점검</span><span class="sxs-lookup"><span data-stu-id="7c28b-104">Check your knowledge</span></span>
  questions:
  - content: <span data-ttu-id="7c28b-105">다음 중 어떤 항목 간의 통신을 보호하는 데 Azure 네트워크 보안 그룹을 사용할 수 있나요?</span><span class="sxs-lookup"><span data-stu-id="7c28b-105">Azure network security group can be used to secure communication between which of the following?</span></span>
    choices:
    - content: <span data-ttu-id="7c28b-106">가상 머신과 인터넷</span><span class="sxs-lookup"><span data-stu-id="7c28b-106">Virtual machines and the internet</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="7c28b-107">네트워크 보안 그룹은 완전히 사용자 지정할 수 있으며, 가상 머신과 주고 받는 네트워크 통신을 완전히 차단하는 기능을 제공합니다.</span><span class="sxs-lookup"><span data-stu-id="7c28b-107">Network security groups are fully customizable, and give you the ability to fully lock down network communication to and from your virtual machines.</span></span>
    - content: <span data-ttu-id="7c28b-108">VNet 내의 가상 머신</span><span class="sxs-lookup"><span data-stu-id="7c28b-108">Virtual machines within a VNet</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="7c28b-109">네트워크 보안 그룹은 완전히 사용자 지정할 수 있으며, 가상 머신과 주고 받는 네트워크 통신을 완전히 차단하는 기능을 제공합니다.</span><span class="sxs-lookup"><span data-stu-id="7c28b-109">Network security groups are fully customizable, and give you the ability to fully lock down network communication to and from your virtual machines.</span></span>
    - content: <span data-ttu-id="7c28b-110">온-프레미스 네트워크의 시스템</span><span class="sxs-lookup"><span data-stu-id="7c28b-110">Systems in an on-premises network</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="7c28b-111">네트워크 보안 그룹은 완전히 사용자 지정할 수 있으며, 가상 머신과 주고 받는 네트워크 통신을 완전히 차단하는 기능을 제공합니다.</span><span class="sxs-lookup"><span data-stu-id="7c28b-111">Network security groups are fully customizable, and give you the ability to fully lock down network communication to and from your virtual machines.</span></span>
    - content: <span data-ttu-id="7c28b-112">위의 모든 항목</span><span class="sxs-lookup"><span data-stu-id="7c28b-112">All of the above</span></span>
      isCorrect: true
      correctExplanation: <span data-ttu-id="7c28b-113">네트워크 보안 그룹은 완전히 사용자 지정할 수 있으며, 가상 머신과 주고 받는 네트워크 통신을 완전히 차단하는 기능을 제공합니다.</span><span class="sxs-lookup"><span data-stu-id="7c28b-113">Network security groups are fully customizable, and give you the ability to fully lock down network communication to and from your virtual machines.</span></span>
  - content: <span data-ttu-id="7c28b-114">다음 중 인터넷 연결 서비스를 네트워크 공격으로부터 보호하는 방법이 아닌 것은 무엇인가요?</span><span class="sxs-lookup"><span data-stu-id="7c28b-114">Which of the following is not a method for protecting internet facing services from network attacks?</span></span>
    choices:
    - content: <span data-ttu-id="7c28b-115">Azure DDoS</span><span class="sxs-lookup"><span data-stu-id="7c28b-115">Azure DDoS</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="7c28b-116">Azure Disk Encryption은 가상 머신 가상 하드 디스크가 노출되지 않도록 보호하지만 네트워크 기반 공격으로부터 보호를 제공하지는 않습니다.</span><span class="sxs-lookup"><span data-stu-id="7c28b-116">Azure Disk Encryption protects your virtual machine virtual hard disks from exposure, but does not provide protection from network based attacks.</span></span>
    - content: <span data-ttu-id="7c28b-117">Azure Application Gateway WAF</span><span class="sxs-lookup"><span data-stu-id="7c28b-117">Azure Application Gateway WAF</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="7c28b-118">Azure Disk Encryption은 가상 머신 가상 하드 디스크가 노출되지 않도록 보호하지만 네트워크 기반 공격으로부터 보호를 제공하지는 않습니다.</span><span class="sxs-lookup"><span data-stu-id="7c28b-118">Azure Disk Encryption protects your virtual machine virtual hard disks from exposure, but does not provide protection from network based attacks.</span></span>
    - content: <span data-ttu-id="7c28b-119">Azure Disk Encryption</span><span class="sxs-lookup"><span data-stu-id="7c28b-119">Azure Disk Encryption</span></span>
      isCorrect: true
      correctExplanation: <span data-ttu-id="7c28b-120">Azure Disk Encryption은 가상 머신 가상 하드 디스크가 노출되지 않도록 보호하지만 네트워크 기반 공격으로부터 보호를 제공하지는 않습니다.</span><span class="sxs-lookup"><span data-stu-id="7c28b-120">Azure Disk Encryption protects your virtual machine virtual hard disks from exposure, but does not provide protection from network based attacks.</span></span>
    - content: <span data-ttu-id="7c28b-121">네트워크 가상 어플라이언스</span><span class="sxs-lookup"><span data-stu-id="7c28b-121">A network virtual appliance</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="7c28b-122">Azure Disk Encryption은 가상 머신 가상 하드 디스크가 노출되지 않도록 보호하지만 네트워크 기반 공격으로부터 보호를 제공하지는 않습니다.</span><span class="sxs-lookup"><span data-stu-id="7c28b-122">Azure Disk Encryption protects your virtual machine virtual hard disks from exposure, but does not provide protection from network based attacks.</span></span>
