### YamlMime:ModuleUnit
uid: learn.design-for-security.6-network-security
title: <span data-ttu-id="bff4d-101">네트워크 보안</span><span class="sxs-lookup"><span data-stu-id="bff4d-101">Network security</span></span>
metadata:
  title: <span data-ttu-id="bff4d-102">네트워크 보안</span><span class="sxs-lookup"><span data-stu-id="bff4d-102">Network security</span></span>
  description: <span data-ttu-id="bff4d-103">이 섹션에서는 네트워크 인프라를 보호하는 방법에 대해 알아보겠습니다.</span><span class="sxs-lookup"><span data-stu-id="bff4d-103">In this unit we'll discuss how to secure your network infrastructure</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 90be1e461ce19e0bd7a18e869397db2d0ab3abfa
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44240756"
durationInMinutes: 5
content: >
  [!include[](includes/6-network-security.md)]
quiz:
  title: <span data-ttu-id="bff4d-104">지식 검사 - 네트워크 보안</span><span class="sxs-lookup"><span data-stu-id="bff4d-104">Knowledge Check - Network security</span></span>
  questions:
  - content: <span data-ttu-id="bff4d-105">다음 중 어떤 항목 간의 통신을 보호하는 데 Azure NSG를 사용할 수 있나요?</span><span class="sxs-lookup"><span data-stu-id="bff4d-105">Azure NSGs can be used to secure communication between which of the following?</span></span>
    choices:
    - content: <span data-ttu-id="bff4d-106">가상 머신과 인터넷 간 통신</span><span class="sxs-lookup"><span data-stu-id="bff4d-106">Communication between virtual machines and the internet</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="bff4d-107">NSG를 사용하여 이 통신 흐름을 보호할 수 있지만 이 선택만 올바른 것은 아닙니다.</span><span class="sxs-lookup"><span data-stu-id="bff4d-107">NSGs can be used to secure this communication flow, but this is not the only correct choice.</span></span>
    - content: <span data-ttu-id="bff4d-108">VNet 내의 가상 머신 간 통신</span><span class="sxs-lookup"><span data-stu-id="bff4d-108">Communication between virtual machines within a VNet</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="bff4d-109">NSG를 사용하여 이 통신 흐름을 보호할 수 있지만 이 선택만 올바른 것은 아닙니다.</span><span class="sxs-lookup"><span data-stu-id="bff4d-109">NSGs can be used to secure this communication flow, but this is not the only correct choice.</span></span>
    - content: <span data-ttu-id="bff4d-110">온-프레미스 네트워크에 있는 시스템과의 통신</span><span class="sxs-lookup"><span data-stu-id="bff4d-110">Communication with systems in an on-premises network</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="bff4d-111">NSG를 사용하여 이 통신 흐름을 보호할 수 있지만 이 선택만 올바른 것은 아닙니다.</span><span class="sxs-lookup"><span data-stu-id="bff4d-111">NSGs can be used to secure this communication flow, but this is not the only correct choice.</span></span>
    - content: <span data-ttu-id="bff4d-112">위의 모든 항목</span><span class="sxs-lookup"><span data-stu-id="bff4d-112">All of the above</span></span>
      isCorrect: true
      correctExplanation: <span data-ttu-id="bff4d-113">NSG는 위의 모든 통신 흐름을 보호하는 데 사용할 수 있습니다.</span><span class="sxs-lookup"><span data-stu-id="bff4d-113">NSGs can be used to secure all of the above communication flows.</span></span>
  - content: <span data-ttu-id="bff4d-114">다음 중 인터넷 연결 서비스를 네트워크 공격으로부터 보호하는 방법이 아닌 것은 무엇인가요?</span><span class="sxs-lookup"><span data-stu-id="bff4d-114">Which of the following is not a method of protecting internet facing services from network attacks?</span></span>
    choices:
    - content: <span data-ttu-id="bff4d-115">Azure DDoS</span><span class="sxs-lookup"><span data-stu-id="bff4d-115">Azure DDoS</span></span>
      isCorrect: false
      incorrectExplanation: '<span data-ttu-id="bff4d-116">Azure DDoS는 DoS 공격에서 인터넷 연결 서비스를 보호하는 데 사용할 수 있습니다.</span><span class="sxs-lookup"><span data-stu-id="bff4d-116">Azure DDoS can be used to protect your internet facing services from a DoS attack.</span></span> '
    - content: <span data-ttu-id="bff4d-117">Azure Application Gateway WAF</span><span class="sxs-lookup"><span data-stu-id="bff4d-117">Azure Application Gateway WAF</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="bff4d-118">Application Gateway WAF는 XSS 및 SQL 삽입과 같은 공격으로부터 인터넷 연결 서비스를 보호하는 데 사용할 수 있습니다.</span><span class="sxs-lookup"><span data-stu-id="bff4d-118">Application Gateway WAF can be used to protect your internet facing services from attacks such as XSS and SQL injection.</span></span>
    - content: <span data-ttu-id="bff4d-119">Azure Disk Encryption</span><span class="sxs-lookup"><span data-stu-id="bff4d-119">Azure Disk Encryption</span></span>
      isCorrect: true
      correctExplanation: <span data-ttu-id="bff4d-120">Azure Disk Encryption은 가상 머신 VHD가 노출되지 않도록 보호하지만 네트워크 기반 공격으로부터 보호를 제공하지는 않습니다.</span><span class="sxs-lookup"><span data-stu-id="bff4d-120">Azure Disk Encryption protects your virtual machine VHDs from exposure, but does not provide protection from network based attacks.</span></span>
    - content: <span data-ttu-id="bff4d-121">네트워크 가상 어플라이언스</span><span class="sxs-lookup"><span data-stu-id="bff4d-121">A network virtual appliance</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="bff4d-122">네트워크 가상 어플라이언스는 인터넷 연결 리소스에 대한 사용자 지정 네트워크 보호를 제공할 수 있습니다.</span><span class="sxs-lookup"><span data-stu-id="bff4d-122">Network virtual appliances can provide customized network protection for your internet facing resources.</span></span>
