### YamlMime:ModuleUnit
uid: learn.store-app-data-with-azure-blob-storage.5-configure-and-initialize-the-client-library
title: <span data-ttu-id="d634f-101">클라이언트 라이브러리 구성 및 초기화</span><span class="sxs-lookup"><span data-stu-id="d634f-101">Configure and initialize the client library</span></span>
metadata:
  title: <span data-ttu-id="d634f-102">클라이언트 라이브러리 구성 및 초기화</span><span class="sxs-lookup"><span data-stu-id="d634f-102">Configure and initialize the client library</span></span>
  description: <span data-ttu-id="d634f-103">클라이언트 라이브러리 구성 및 초기화</span><span class="sxs-lookup"><span data-stu-id="d634f-103">Configure and initialize the client library</span></span>
  ms.openlocfilehash: c7cc43321a9dc94f71e7689a47ca31e8fe7c774c
  ms.sourcegitcommit: 12b4711682dac42f742a944fd9baa0e9dd09cf35
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 08/22/2018
  ms.locfileid: "40442793"
durationInMinutes: 10
interactive: bash-editor
content: '[!include[](includes/5-configure-and-initialize-the-client-library.md)]'
