### YamlMime:ModuleUnit
uid: learn.store-app-data-with-azure-blob-storage.5-configure-and-initialize-the-client-library
title: <span data-ttu-id="6973c-101">클라이언트 라이브러리 구성 및 초기화</span><span class="sxs-lookup"><span data-stu-id="6973c-101">Configure and initialize the client library</span></span>
metadata:
  title: <span data-ttu-id="6973c-102">클라이언트 라이브러리 구성 및 초기화</span><span class="sxs-lookup"><span data-stu-id="6973c-102">Configure and initialize the client library</span></span>
  description: <span data-ttu-id="6973c-103">클라이언트 라이브러리 구성 및 초기화</span><span class="sxs-lookup"><span data-stu-id="6973c-103">Configure and initialize the client library</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: bedd297c48ead2c2aadba57e57e3bb8b965344fb
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47147367"
durationInMinutes: 10
interactive: bash-editor
azureSandbox: true
content: '[!include[](includes/5-configure-and-initialize-the-client-library.md)]'
