### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.1-create-azure-iot-central-application
title: Azure IoT Central 응용 프로그램 만들기
metadata:
  title: Azure IoT Central 응용 프로그램 만들기
  description: Azure IoT Central 응용 프로그램 만들기
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 98e9a83d594bc3611f3048909b7d238ea289901e
  ms.sourcegitcommit: 8a009788ee73c5d7caa6cd4f1105260c5cc9b846
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/22/2018
  ms.locfileid: "46570455"
durationInMinutes: 5
content: '[!include[](includes/1-create-azure-iot-central-application.md)]'
