### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.3-connect-your-application-to-simulator
title: <span data-ttu-id="ca9a6-101">시뮬레이션된 커피 머신을 응용 프로그램에 연결</span><span class="sxs-lookup"><span data-stu-id="ca9a6-101">Connect your simulated coffee machine to the application</span></span>
metadata:
  title: <span data-ttu-id="ca9a6-102">시뮬레이션된 커피 머신을 응용 프로그램에 연결</span><span class="sxs-lookup"><span data-stu-id="ca9a6-102">Connect your simulated coffee machine to the application</span></span>
  description: <span data-ttu-id="ca9a6-103">시뮬레이션된 커피 머신을 응용 프로그램에 연결</span><span class="sxs-lookup"><span data-stu-id="ca9a6-103">Connect your simulated coffee machine to the application</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 92bb8af9f5ffdd6f1ebf9f8412ff3d64825a2547
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47142950"
interactive: bash
azureSandbox: true
durationInMinutes: 15
content: '[!include[](includes/3-connect-your-application-to-simulator.md)]'
