### YamlMime:ModuleUnit
uid: learn.make-your-virtual-machines-highly-available.4-configure-a-load-balancer-in-azure
title: Azure에서 부하 분산 장치 구성
metadata:
  title: Azure에서 부하 분산 장치 구성
  description: Azure에서 부하 분산 장치 구성
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: d215de8466824dfb203b3472207a44b5d1364828
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44238204"
durationInMinutes: 5
content: '[!include[](includes/4-configure-a-load-balancer-in-azure.md)]'
