### YamlMime:ModuleUnit
uid: learn.make-your-virtual-machines-highly-available.5-exercise-configure-a-load-balancer-in-azure
title: 연습 - Azure에서 부하 분산 장치 구성
metadata:
  title: 연습 - Azure에서 부하 분산 장치 구성
  description: 연습 - Azure에서 부하 분산 장치 구성
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 707508ce42b59332c47d86c0755088e2573826c9
  ms.sourcegitcommit: b6f5aa15bae13cb0f53667fba1d404b7bec76f67
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/17/2018
  ms.locfileid: "45757924"
azureSandbox: true
durationInMinutes: 15
content: '[!include[](includes/5-exercise-configure-a-load-balancer-in-azure.md)]'
