### YamlMime:ModuleUnit
uid: learn.make-your-virtual-machines-highly-available.6-exercise-configure-a-load-balancer-in-azure
title: <span data-ttu-id="16970-101">연습 - Azure에서 부하 분산 장치 구성</span><span class="sxs-lookup"><span data-stu-id="16970-101">Exercise - Configure a load balancer in Azure</span></span>
metadata:
  title: <span data-ttu-id="16970-102">연습 - Azure에서 부하 분산 장치 구성</span><span class="sxs-lookup"><span data-stu-id="16970-102">Exercise - Configure a load balancer in Azure</span></span>
  description: <span data-ttu-id="16970-103">연습 - Azure에서 부하 분산 장치 구성</span><span class="sxs-lookup"><span data-stu-id="16970-103">Exercise - Configure a load balancer in Azure</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: d653a821bf0b0522ca085de5af23f830e6d24041
  ms.sourcegitcommit: 58e9d7fbb111af9b27ed819e4b79ba4a4e6e8a9c
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/21/2018
  ms.locfileid: "46513190"
azureSandbox: true
durationInMinutes: 15
content: '[!include[](includes/6-exercise-configure-a-load-balancer-in-azure.md)]'
