### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-web-apps.5-exercise-create-an-asp.net-core-web-application-on-linux
title: 연습 - Linux에서 ASP.NET Core 응용 프로그램 만들기
metadata:
  title: 연습 - Linux에서 ASP.NET Core 응용 프로그램 만들기
  description: 연습 - Linux에서 ASP.NET Core 응용 프로그램 만들기
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: d568d2d92f827fea2713d8c79f29fc646033d588
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44234957"
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-an-asp.net-core-web-application-on-linux.md)]'
