### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-web-apps.5-exercise-create-an-asp.net-core-web-application-on-linux
title: <span data-ttu-id="08ba3-101">연습 - Linux에서 ASP.NET Core 응용 프로그램 만들기</span><span class="sxs-lookup"><span data-stu-id="08ba3-101">Exercise - Create an ASP.NET Core application on Linux</span></span>
metadata:
  title: <span data-ttu-id="08ba3-102">연습 - Linux에서 ASP.NET Core 응용 프로그램 만들기</span><span class="sxs-lookup"><span data-stu-id="08ba3-102">Exercise - Create an ASP.NET Core application on Linux</span></span>
  description: <span data-ttu-id="08ba3-103">연습 - Linux에서 ASP.NET Core 응용 프로그램 만들기</span><span class="sxs-lookup"><span data-stu-id="08ba3-103">Exercise - Create an ASP.NET Core application on Linux</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 1755b3e9fde0c7c3e4f812551960035a76f23c88
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47140854"
interactive: bash
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-an-asp.net-core-web-application-on-linux.md)]'
