### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-app-service.5-exercise-create-an-asp.net-core-web-application-on-linux
title: <span data-ttu-id="1b73b-101">연습 - Linux에서 ASP.NET Core 응용 프로그램 만들기</span><span class="sxs-lookup"><span data-stu-id="1b73b-101">Exercise - Create an ASP.NET Core application on Linux</span></span>
metadata:
  title: <span data-ttu-id="1b73b-102">연습 - Linux에서 ASP.NET Core 응용 프로그램 만들기</span><span class="sxs-lookup"><span data-stu-id="1b73b-102">Exercise - Create an ASP.NET Core application on Linux</span></span>
  description: <span data-ttu-id="1b73b-103">연습 - Linux에서 ASP.NET Core 응용 프로그램 만들기</span><span class="sxs-lookup"><span data-stu-id="1b73b-103">Exercise - Create an ASP.NET Core application on Linux</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 3c73c9ee2da417fcbfb91cc5beeae6a13659c5e7
  ms.sourcegitcommit: 8fbdc9990a51065cb16b1ff4644ca3af93798a5e
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/14/2018
  ms.locfileid: "45586314"
interactive: bash
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-an-asp.net-core-web-application-on-linux.md)]'
