### YamlMime:ModuleUnit
uid: learn.design-for-performance-and-scalability.5-identify-performance-bottlenecks-in-your-application
title: <span data-ttu-id="d6e1e-101">응용 프로그램에서 성능 병목 상태 식별</span><span class="sxs-lookup"><span data-stu-id="d6e1e-101">Identify performance bottlenecks in your application</span></span>
metadata:
  title: <span data-ttu-id="d6e1e-102">응용 프로그램에서 성능 병목 상태 식별</span><span class="sxs-lookup"><span data-stu-id="d6e1e-102">Identify performance bottlenecks in your application</span></span>
  description: <span data-ttu-id="d6e1e-103">이 단원에서는 응용 프로그램에서 성능 병목 상태를 식별하는 방법을 알아보겠습니다.</span><span class="sxs-lookup"><span data-stu-id="d6e1e-103">In this unit we'll discuss how to identify performance bottlenecks in your application</span></span>
  ms.openlocfilehash: 0b5ab3a983a4b3dfc3a76c914b6a565f3ee7ed2c
  ms.sourcegitcommit: 926510a198d738c5726081f6d7994fe9b6fc6edb
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 08/29/2018
  ms.locfileid: "43180381"
durationInMinutes: 5
content: >
  [!include[](includes/5-identify-performance-bottlenecks-in-your-application.md)]
quiz:
  title: <span data-ttu-id="d6e1e-104">지식 검사 - 응용 프로그램에서 성능 병목 상태 식별</span><span class="sxs-lookup"><span data-stu-id="d6e1e-104">Knowledge Check - Identify performance bottlenecks in your application</span></span>
  questions:
  - content: <span data-ttu-id="d6e1e-105">다음 중 Application Insights를 가장 잘 나타낸 설명은 어느 것인가요?</span><span class="sxs-lookup"><span data-stu-id="d6e1e-105">Which of the following best describes Application Insights?</span></span>
    choices:
    - content: <span data-ttu-id="d6e1e-106">Azure의 모니터링 요구를 위한 단일 창</span><span class="sxs-lookup"><span data-stu-id="d6e1e-106">A single pane of glass for our monitoring needs in Azure</span></span>
      isCorrect: false
    - content: <span data-ttu-id="d6e1e-107">상태 엔드포인트 모니터링 패턴 구현</span><span class="sxs-lookup"><span data-stu-id="d6e1e-107">An implementation of the health endpoint monitoring pattern</span></span>
      isCorrect: false
    - content: <span data-ttu-id="d6e1e-108">인프라 및 응용 프로그램에서 로그 수집이 가능한 작업 영역</span><span class="sxs-lookup"><span data-stu-id="d6e1e-108">A workspace to enable collection of logs across infrastructure and applications</span></span>
      isCorrect: false
    - content: <span data-ttu-id="d6e1e-109">웹 응용 프로그램의 가용성, 성능 및 사용 현황을 모니터하는 서비스</span><span class="sxs-lookup"><span data-stu-id="d6e1e-109">A service to monitor availability, performance, and usage of web applications</span></span>
      isCorrect: true
  - content: <span data-ttu-id="d6e1e-110">Log Analytics를 사용하여 사용자 지정 로그 및 메트릭을 추적할 수 있습니다.</span><span class="sxs-lookup"><span data-stu-id="d6e1e-110">You can use Log Analytics to track custom logs and metrics.</span></span>
    choices:
    - content: <span data-ttu-id="d6e1e-111">True</span><span class="sxs-lookup"><span data-stu-id="d6e1e-111">True</span></span>
      isCorrect: true
    - content: <span data-ttu-id="d6e1e-112">False</span><span class="sxs-lookup"><span data-stu-id="d6e1e-112">False</span></span>
      isCorrect: false
