### YamlMime:ModuleUnit
uid: learn.design-for-performance-and-scalability.5-identify-performance-bottlenecks-in-your-application
title: 응용 프로그램에서 성능 병목 상태 식별
metadata:
  title: 응용 프로그램에서 성능 병목 상태 식별
  description: 이 단원에서는 응용 프로그램에서 성능 병목 상태를 식별하는 방법을 알아보겠습니다.
  ms.openlocfilehash: 79f99fe822392cb112e6af9086aa14de6eb07fc3
  ms.sourcegitcommit: 2df436853854bfcb39bc82ee461d7011bf8531ca
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/04/2018
  ms.locfileid: "43675344"
durationInMinutes: 5
content: >
  [!include[](includes/5-identify-performance-bottlenecks-in-your-application.md)]
quiz:
  title: 지식 검사 - 응용 프로그램에서 성능 병목 상태 식별
  questions:
  - content: 다음 중 Application Insights를 가장 잘 나타낸 설명은 어느 것인가요?
    choices:
    - content: Azure의 모니터링 요구를 위한 단일 창
      isCorrect: false
      incorrectExplanation: Application Insights는 응용 프로그램 성능에 대한 풍부한 데이터를 제공할 수 있지만 포괄적인 Azure 모니터링 솔루션이 아닙니다.
    - content: 상태 엔드포인트 모니터링 패턴 구현
      isCorrect: false
      incorrectExplanation: 상태 엔드포인트 모니터링 패턴은 전반적인 상태에 대해 응용 프로그램에서 노출된 모니터링 엔드포인트에 중점을 둡니다.
    - content: 인프라 및 응용 프로그램에서 로그를 수집할 수 있는 작업 영역
      isCorrect: false
      incorrectExplanation: Log Analytics는 인프라 및 응용 프로그램에서 로그를 수집할 수 있는 작업 영역입니다.
    - content: 웹 응용 프로그램의 가용성, 성능 및 사용량을 모니터링하는 서비스
      isCorrect: true
      correctExplanation: Application Insights는 웹 응용 프로그램의 가용성, 성능 및 사용량을 모니터링하는 서비스입니다.
  - content: Log Analytics를 사용하여 사용자 지정 로그 및 메트릭을 추적할 수 있습니다.
    choices:
    - content: "True"
      isCorrect: true
      correctExplanation: 사용자 지정 로그 및 메트릭의 경우 HTTP 데이터 수집기 API를 사용하여 REST API 클라이언트에서 Log Analytics에 데이터를 작성하거나 Azure Logic App을 사용하여 사용자 지정 워크플로에서 데이터를 작성할 수 있습니다.
    - content: "False"
      isCorrect: false
      incorrectExplanation: 사용자 지정 로그 및 메트릭의 경우 HTTP 데이터 수집기 API를 사용하여 REST API 클라이언트에서 Log Analytics에 데이터를 작성하거나 Azure Logic App을 사용하여 사용자 지정 워크플로에서 데이터를 작성할 수 있습니다.
