### YamlMime:ModuleUnit
uid: learn.design-for-security.6-network-security
title: <span data-ttu-id="8a9d9-101">네트워크 보안</span><span class="sxs-lookup"><span data-stu-id="8a9d9-101">Network security</span></span>
metadata:
  title: <span data-ttu-id="8a9d9-102">네트워크 보안</span><span class="sxs-lookup"><span data-stu-id="8a9d9-102">Network security</span></span>
  description: <span data-ttu-id="8a9d9-103">이 섹션에서는 네트워크 인프라를 보호하는 방법에 대해 알아보겠습니다.</span><span class="sxs-lookup"><span data-stu-id="8a9d9-103">In this unit we'll discuss how to secure your network infrastructure</span></span>
  ms.openlocfilehash: f98e9f24b46119fda8be58fb4a06f8f15d60ed66
  ms.sourcegitcommit: 1663afb13d55c1fce5f2dc4c0f78ef2d74902c33
  ms.translationtype: HT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 08/31/2018
  ms.locfileid: "43367084"
durationInMinutes: 5
content: >
  [!include[](includes/6-network-security.md)]
quiz:
  title: <span data-ttu-id="8a9d9-104">지식 검사 - 네트워크 보안</span><span class="sxs-lookup"><span data-stu-id="8a9d9-104">Knowledge Check - Network security</span></span>
  questions:
  - content: <span data-ttu-id="8a9d9-105">Azure App Service에서 웹 응용 프로그램을 실행하면 응용 프로그램이 완벽하게 보호되므로 추가 보안을 제공할 필요가 없습니다.</span><span class="sxs-lookup"><span data-stu-id="8a9d9-105">When running web applications on Azure App Service, your application is fully secure and you do not need to provide additional security protections.</span></span>
    choices:
    - content: <span data-ttu-id="8a9d9-106">정답</span><span class="sxs-lookup"><span data-stu-id="8a9d9-106">True</span></span>
      isCorrect: false
    - content: <span data-ttu-id="8a9d9-107">오답</span><span class="sxs-lookup"><span data-stu-id="8a9d9-107">False</span></span>
      isCorrect: true
  - content: <span data-ttu-id="8a9d9-108">다음 중 인터넷 연결 서비스를 네트워크 공격으로부터 보호하는 방법이 아닌 것은 무엇입니까?</span><span class="sxs-lookup"><span data-stu-id="8a9d9-108">Which of the following is not a method of protecting internet facing services from network attacks?</span></span>
    choices:
    - content: <span data-ttu-id="8a9d9-109">Azure DDoS</span><span class="sxs-lookup"><span data-stu-id="8a9d9-109">Azure DDoS</span></span>
      isCorrect: false
    - content: <span data-ttu-id="8a9d9-110">Azure Application Gateway WAF</span><span class="sxs-lookup"><span data-stu-id="8a9d9-110">Azure Application Gateway WAF</span></span>
      isCorrect: false
    - content: <span data-ttu-id="8a9d9-111">Azure Disk Encryption</span><span class="sxs-lookup"><span data-stu-id="8a9d9-111">Azure Disk Encryption</span></span>
      isCorrect: true
    - content: <span data-ttu-id="8a9d9-112">네트워크 가상 어플라이언스</span><span class="sxs-lookup"><span data-stu-id="8a9d9-112">A network virtual appliance</span></span>
      isCorrect: false
